pygments: true
safe: true
lsi: false
encoding: utf-8

# Fill these out with your site specific information.
name: Tennu
title: "The Tennu framework for IRC Bots in JavaScript"
description: "Tennu is a framework for event and promise driven programming in JavaScript"
keywords: "tennu, irc, open source, javascript, library, framework, irc bot"
subheader: "Simple Robust IRC Bots"

navigation:
  - text: Overview
    url: /index
    group: home
  - text: Documentation
    url: /documentation/
    group: docs
  - text: Plugins
    url: /plugins/
    group: plugins
